### ISSUE TITLE
Create function in single or multiple .py files

### ISSUE THREAD

**Issue by manvirsingh96** [UBC-MDS/socceranalysis_python#7]
Should we create our functions in the same .py file since all of our functions are independent of each other?

**Comment by louiewang820** [comment]
Hi Manvir. We can do that but I remember when we did IA1, the authors created different py scripts for different functions under the same folder. I think we can do the same because if we all work on the same py script, we might  encounter merging conflicts quite often if we want to make a minor change.

├── src
│   └── pycounts
│       ├── __init__.py
│       ├── plotting.py  <--------
│       └── pycounts.py

Although pycounts has three functions, the final one depends on the first two. Since all of our four functions are independent, it is not necessary to put them in the same script. We can put them in the same script in our final version of the project as no more changes are needed.

**Comment by manvirsingh96** [comment]
Added my function to a separate file
